### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by fmusoni**
Uploaded additional cyclone floods sub-layer as requested by INGD (Gigo) 
[Zambezia1.json.zip](https://github.com/onaio/ingc-mozambique-data/files/8343733/Zambezia1.json.zip)
[Nampula.json.zip](https://github.com/onaio/ingc-mozambique-data/files/8343740/Nampula.json.zip)
[Namacurra.json.zip](https://github.com/onaio/ingc-mozambique-data/files/8343742/Namacurra.json.zip)
[Namacurra 22.json.zip](https://github.com/onaio/ingc-mozambique-data/files/8343746/Namacurra.22.json.zip)
[Namacura_date_16.json.zip](https://github.com/onaio/ingc-mozambique-data/files/8343750/Namacura_date_16.json.zip)
[Maganja da Costa.json.zip](https://github.com/onaio/ingc-mozambique-data/files/8343753/Maganja.da.Costa.json.zip)
[Namacurra 17.json.zip](https://github.com/onaio/ingc-mozambique-data/files/8343730/Namacurra.17.json.zip)

### CODE REVIEW

**Comment by baokiddy** [comment]
@fmusoni I reviewed your update and noticed that you haven't create the json files with the correct format. For each layer you need a json (layer definition) and geojson file (data source). To showcase this, I have created 2 dummy layers using the 2 Namacurra geojson files I had access to. Since I had access I created mbtiles but I've also created a flood layer template json so you can use that as reference. The steps of the process are as follows:
1. Copy the template file into the folder
2. Open the copy and update the details on any text that is fully capitalized
3. Add the GeoJSON file into the cyclone flood zone folder and add the GeoJSON url into the json file (reference my layers for the format)
4. Once you complete this process , push the changes to your branch.  

I am on leave for tomorrow and Monday but will notify the team to look out for your message. Please email the Ona support email and CC Alessandro for any concerns or additional questions.

cc @alepietrobon @kahummer

**Comment by fmusoni** [comment]
@kahummer the geojson files are too large, which prevents me for pushing the changes. Do you have any advice on how to proceed? Thanks!

**Comment by fmusoni** [comment]
@kahummer Are you pushing large geojson files to Git Large file storage? Thanks

**Comment by kahummer** [comment]
@fmusoni Your right, we will need to convert the geojsons to mbtiles then upload them to mapbox considering the size. Is this something @baokiddy had taken you through ? If no we will have to do it then reference the tiles as shown [here ](https://github.com/onaio/ingc-mozambique-data/pull/161/commits/77fee6845a53cfde939a73358237e326fc316e3c#diff-866bac2530b0fe32e896f1878e6d0e63250cab93c54d82dbf71322ce50e63148R4-R6)

**Comment by fmusoni** [comment]
@kahummer thank you for the confirmation. I created a few pull requests, and I believe only two files - ones with larger geojson files, will not pass the review. Could you kindly confirm? Do you have a resource, guidance, I can use to convert geojson files to mbtiles? I will also do some research on Youtube

**Review by baokiddy — APPROVED** [review]

**Pull request merged**
